### ISSUE TITLE
How to launch on 1.7.10

### ISSUE THREAD

**Issue by dimti** [airbreather/YALSM#5]
Hello

I have YALSM 2.1.5 and start own server

But i not see recipe in NEI and not see config file YALSM.cfg on config folder.

If a run yalsm 2.1.3 - my console generate error for me (many java exceptions). How to fix that situation and start to work this mod?

**Comment by airbreather** [comment]
What, specifically, have you tried?  Please list the exact steps you take.

**Comment by dimti** [comment]
Sorry of the obfuscation my first message)

Situation is simple.
1.7.10 FML
I put mods/yalsm-2.1.5-mc1.8.9.jar and launch client
In logs one record

```[17:57:23] [Client thread/INFO]: FML has found a non-mod file yalsm-2.1.5-mc1.8.9.jar in your mods directory. It will now be injected into your classpath. This could severe stability issues, it should be removed if possible.```

And in the game - i dont not see this mod and do not see crafting recipies with Rotten flesh in NEI

**Comment by airbreather** [comment]
Only 2.1.3 will work with MC 1.7.10.  You'll also need to put an appropriate version of airbreathercore into the mods folder.

For 1.7.10, put these two files into your mods folder, delete all the other YALSM / airbreathercore attempts, and try again:

Mod | URL
--- | ---
YALSM 2.1.3 | https://goo.gl/Xd8kU6
airbreathercore 1.0.0a | https://goo.gl/RquU1V

**Comment by dimti** [comment]
Ja-ja. now works
