### ISSUE TITLE
Add support for 1.11.2

### ISSUE THREAD

**Issue by The-Fireplace** [airbreather/YALSM#7]
If it does already support 1.11.2, could you update the file on CF to say so, that way we can install it from the launcher?

On a side note, do you have a Maven or Ivy set up for the mod? Or is the patchwork flesh registered to OreDIctionary?

**Comment by airbreather** [comment]
Latest CurseForge files now say that 1.11.2 is supported (tested it this morning).

I don't have Maven or Ivy set up for this.  Is that what the cool kids have started doing these days?  For a few years now, I've just been in "maintenance mode" with my mods, only doing the bare minimum needed to keep them working as-is with the newer Forge and Minecraft versions.

The only Ore Dictionary registration I think I do in any of my mods is that pig-manure-mod registers the manure item as "dyeBrown"... other than that, there were no keys in common use that would have made sense for anything else to piggyback onto.  Do you think that's changed in recent times?

**Comment by The-Fireplace** [comment]
Quite a few major mods have Maven now, and a few have Ivy instead of Maven. It makes developing add-ons or compat pretty easy.

As for OreDictionary, if you don't want to set up a Maven, the quickest solution for my goal here would be to register the Patchwork Flesh to OreDictionary, as I want to use it in one of my recipes when YALSM is loaded.
